require "gmeier.plugins"
require "gmeier.remap"
require "gmeier.telescope"
require "gmeier.treesitter"
require "gmeier.undotree"
require "gmeier.fugitive"
require "gmeier.lsp"
require "gmeier.config"
